env:
  global:
    - NODE_ENV=testing
language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - postgresql
addons:
  chrome: stable
cache:
  directories:
    - 'node_modules'
before_script:
  - psql -c 'create database quickdecks_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - npx knex migrate:down --env=testing
  - npx knex migrate:latest --env=testing

script: 
  - npm test
  - bash build.sh || travis_terminate 1;
  - bash deploy.sh || travis_terminate 1;

notifications:
  email: true
